apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dc6f
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dc6f
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dc6f
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dc6f
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dc6f
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xkkx-tenant/rhtap-demo-app/hacbs-test-project-dc6f@sha256:8b09951bd3f8fc01f14e62f8d4383de8c4f552aef4ae51174d6a862974114da5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
