apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-dc6f
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xkkx-tenant/rhtap-demo-app/hacbs-test-project-dc6f@sha256:cc51a1654ad84366018d1aa8314ac6347024a81d4cb356963b06492837e5ed13
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
